- registry/package.json
- registry/server/app.ts
- registry/server/apps/interfaces/App.ts
- registry/server/apps/routes/createApps.ts
- registry/server/apps/routes/deleteApps.ts
- registry/server/apps/routes/getApps.ts
- registry/server/apps/routes/index.ts
- registry/server/apps/routes/updateApp.ts
- registry/server/apps/services/preInsertApps.ts
- registry/server/apps/services/prepareAppsToInsert.ts
- registry/server/db.ts
It needs to change the destination into `feature/app-routes` after PR of `feature/get-apps-route` will be merged
> Add create, update, delete apps routes

- ilc/client.js
- ilc/package.json
- ilc/systemjs/build.js
**Important**! Also, need to re-check it when you are going to review it
> Revert removing of SystemJS CSS extra plugin

- devFragments/fetchWithCache/package.json
- devFragments/fetchWithCache/webpack.config.js
- devFragments/navbar/package.json
- devFragments/navbar/webpack.config.js
- devFragments/news-ssr/config/webpack.client_spa.config.js
- devFragments/news-ssr/package.json
- devFragments/people/package.json
- devFragments/people/webpack.config.js
- devFragments/planets/package.json
- devFragments/planets/webpack.config.js
- devFragments/system/package.json
- devFragments/system/webpack.config.js
- ilc/systemjs/build.js
- ilc/systemjs/systemjs-transform-loader.js
Remove wrappers in Webpack configs and move wrappers sense into system js plugin
> On-the-fly conversion of the AMD modules that use "define" into "ILC.define"

- ilc/package.json
- ilc/server/tailor/request-handler.js
- ilc/server/tailor/seobots-guard-stream.js
> Logic to handle errors more strictly in case we're dealing with Bots

- ilc/server/tailor/configs-injector.js
- ilc/server/tailor/factory.js
It relates to https://github.com/StyleT/tailorx/pull/18
> Add ignoring newrelic script during tailor x parsing

- ilc/package.json
This reverts commit 955ee2e120b1fbfa955e20f885cabc0960a2cf87, reversing
changes made to eff12df244838f6b311288b1d1b1c574b94625d3.
> Revert "Merge pull request #78 from namecheap/feature/update-single-spa"

- ilc/client.js
New: https://take.ms/MztBp
Old: https://take.ms/Id88i
> feat: initing apps in separate mactotasks

- ilc/package.json
- ilc/server/tailor/configs-injector.js
- ilc/server/tailor/factory.js
**It depends on https://github.com/StyleT/tailorx/pull/20/files**
> Preload styles firstly and load scripts then

- ilc/client.js
- ilc/client/AsyncBootUp.spec.js
- ilc/client/isActiveFactory.js
- ilc/client/isActiveFactory.spec.js
Need to change dest to `master` after `cover/async-boot-up` is going to be merged
> Cover is active factory with karma tests

- e2e/codecept.conf.js
- e2e/spec/hooks.spec.e2e.ts
- e2e/spec/pages/hooks.ts
- e2e/typings/steps.d.ts
- ilc/client/navigationEvents/setupEvents.spec.js
- registry/server/seeds/03_routes.ts
- registry/server/seeds/04_route_slots.ts
Merge after:
* https://github.com/namecheap/ilc-plugins-sdk/pull/5
* https://github.com/namecheap/ilc/pull/261
* https://github.com/namecheap/ilc-demo-apps/pull/47
> feat: cover hooks with e2e tests

- ilc/client/AsyncBootUp.js
- ilc/client/AsyncBootUp.spec.js
- ilc/client/ilcConfig.js
- ilc/client/registerSpaApps.js
- ilc/server/tailor/fragment-hooks.js
- ilc/systemjs/systemjs-override-importmap.js
- ilc/systemjs/systemjs-override-importmap.spec.js
This is a preparation for Parcels support
> feat: now it's possible to import app bundle by app's name

- ilc/package.json
- ilc/server/tailor/parse-override-config.js
- ilc/server/tailor/parse-override-config.spec.js
Allows to fit more data into `ILC-overrideConfig` cookie
> feat: added ability to use compression for config override cookie

- ilc/client/ClientRouter.js
- ilc/client/ClientRouter.spec.js
- ilc/client/navigationEvents/setupEvents.js
- ilc/client/registerSpaApps.js
- ilc/client/utils.js
- ilc/client/utils.spec.js
- ilc/package-lock.json
- ilc/package.json
…nmounting and mounting processes
> feat: the same app with different props is just updated, instead of unmounting and mounting processes

- docs/routing/route_configuration_options.md
This is necessary for correct display on gh-pages.
> docs: small visual fix

- ilc/server/app.js
- ilc/server/errorHandler/ErrorHandler.js
extend logs info to make debug easier
> chore: add request info to logs to make debug easier

- registry/server/app.ts
- registry/server/auth.ts
- registry/server/index.ts
- registry/tests/appRoutes.spec.ts
- registry/tests/apps.spec.ts
- registry/tests/auth.spec.ts
- registry/tests/authEntities.spec.ts
- registry/tests/common.ts
- registry/tests/config.spec.ts
- registry/tests/public.spec.ts
- registry/tests/routerDomains.spec.ts
- registry/tests/settings.spec.ts
- registry/tests/sharedLibs.spec.ts
- registry/tests/sharedProps.spec.ts
- registry/tests/templates.spec.ts
- registry/tests/test.spec.ts
- registry/tests/versioning.spec.ts
strategy due to error that `openid` strategy is not registered.
> fix: attempt to fix issue when user is unable to login via openid 

- docs/assets/demo-website.svg
> Update badge for demo website

- ilc/package-lock.json
- ilc/package.json
- ilc/server/tailor/factory.js
- ilc/server/tailor/fragment-hooks.js
Get rid of dependency from not our internal space.
> chore: switch to namecheap/tailorx

- ilc/server/tailor/fragment-hooks.js
- ilc/server/tailor/request-fragment.js
- ilc/server/tailor/server-router.js
add operationID and enhance logs
> Add logs for tailor logic

- ilc/client/WrapApp.js
- ilc/client/WrapApp.spec.js
AppWrapperData contains appId that will allow to handle SSR data for ReactApp
> NPF-2443 pass wrapper info

- ilc/client/Client.js
- ilc/client/configuration/IlcConfigRoot.js
- ilc/server/tailor/configs-injector.js
- registry/client/src/sharedLibs/Edit.js
- registry/client/src/sharedLibs/Show.js
- registry/server/migrations/20220928161155_shared-lib-add-localization.ts
- registry/server/routes/config.ts
- registry/server/sharedLibs/interfaces/index.ts
* Shared Libs contains l10nManifest
* API for shared lib extended
* Client side API for read Shared Lib config
> Add localisation to shared libs

- ilc/client/ErrorHandlerManager/ErrorHandlerManager.js
- ilc/client/ErrorHandlerManager/ErrorHandlerManager.spec.js
should be replaced with custom reporter plugin
> feat(ErrorHandler): Removed newrelic notice error invocation

- .prettierignore
- ilc/common/wrapWithCache.js
- ilc/server/GuardManager.spec.js
- ilc/server/app.js
- ilc/server/context/context.js
- ilc/server/errorHandler/ErrorHandler.spec.js
- ilc/server/i18n.spec.js
- ilc/server/index.js
- ilc/server/registry/Registry.js
* update log information
* add config filecheck sum to understand when cache is stale on node
* pass request id to logs
> chore: put request id to caching logs and log file checksum

- ilc/client/Client.js
- ilc/newrelic.js
add matchCurrentRoute method that allow to match URL w/o knowledge about locale
> feat: add matchCurrentRoute method

- ilc/server/errorHandler/ErrorHandler.js
- ilc/server/errorHandler/ErrorHandler.spec.js
- registry/server/common/services/json.ts
- registry/tests/services/settingsService.spec.ts
- option.reportError support not only ErrorCollector but also Logger level
> chore: decrease log level for local development error

- ilc/babel.config.js
- ilc/karma.conf.js
- ilc/nyc.config.js
- ilc/package-lock.json
- ilc/package.json
- registry/.mocharc.json
- registry/.nycrc.json
- registry/package-lock.json
- registry/package.json
Preparation work for code coverage report PR #525
>  fix code coverage reporting in ilc/client/server, registry

- .github/workflows/ci.yml
- .github/workflows/merge-registry-coverage.sh
- registry/server/migrations/20201228201314_route_meta.ts
- registry/server/migrations/20210405182655_routes_domainId.ts
- registry/server/migrations/20210426163602_routes_orderPosIsNullable.ts
Run registry unit tests on SQLite, MySQL and PostgreSQL
Run E2E tests on MySQL and PostgreSQL
Combine coverage reports from all databases
> feat(ci): test run on multiple databases

- registry/package.json
- registry/server/common/services/assets/AssetsDiscovery.ts
- registry/server/util/axiosErrorTransformer.ts
- registry/server/util/logger.ts
fix Axios error serialization
fix info in asset discover warn log
better dotenv injection
> fix(registry): fix info in asset discover warn log

- ilc/package-lock.json
- ilc/package.json
- ilc/server/i18n.js
- ilc/server/i18n.spec.js
- ilc/tsconfig.json
- registry/package-lock.json
- registry/package.json
- start_all.js
Will update ilc-plugins-sdk once it's merged.
> feat(ilc-server): pass additional methods to i18nParamsDetectionPlugin

- ilc/client/BundleLoader.spec.js
- ilc/client/ParcelApi.spec.js
- ilc/client/composeAppSlotPairsToRegister.spec.js
- ilc/package.json
- ilc/server/app.js
- ilc/server/registry/Registry.js
- ilc/server/registry/Registry.spec.js
- ilc/server/tailor/request-fragment.spec.js
- ilc/server/tailor/server-router.spec.js
- ilc/tests/helpers.js
Additionally, fix race condition in Registry getConfig()
> fix(ilc-server): catch errors in request/response fastify hooks

- .gitignore
- .vscode/launch.json
- ilc/package-lock.json
- ilc/package.json
- ilc/server/app.js
- ilc/server/serveStatic.js
fix issue with crash on sourcemap load
remove redundant cors middleware
> feat(ilc/client): add config for browser debug;

- ilc/package-lock.json
- ilc/package.json
- ilc/server/tailor/configs-injector.js
- ilc/server/tailor/configs-injector.spec.js
- install_all.js
Remove outdated polyfills as polyfill.io is not available.
> fix(ilc): remove polyfills

- registry/server/db/versioning.ts
Comparation attached in the ticket.
> fix(ilc-registry/server): optimize versioning query

- registry/server/common/services/assets/AssetsDiscovery.ts
It is impossible to see locally because locally newrelic agent is disabled, putting completely other implementation of the function.
> fix: correct newrelic call for background process instrumentation.

- .github/workflows/ci.yml
- ilc/client/ClientRouter.js
- ilc/client/CssTrackedApp.js
- ilc/client/CssTrackedApps.spec.js
Fixed removing embedded application CSS link when application is unmounted during route change
> fix(ilc): fix removing css link for embedded app

- ilc/common/UrlProcessor.js
- ilc/common/UrlProcessor.spec.js
- ilc/server/app.spec.js
- ilc/server/i18n.js
Switch to a safer protection from openredirect that does additional end-sanitizing
> fix: another case of open redirect

- .github/workflows/ci.yml
- ilc/client/CanonicalTagHandler.spec.ts
- ilc/client/CanonicalTagHandler.ts
- ilc/client/Client.js
- ilc/server/services/CanonicalTagService.spec.ts
- ilc/server/services/CanonicalTagService.ts
- ilc/server/tailor/configs-injector.js
- ilc/server/tailor/configs-injector.spec.js
- ilc/server/types/RegistryConfig.ts
- registry/client/src/routerDomains/Edit.js
- registry/client/src/routerDomains/List.js
- registry/client/src/routerDomains/Show.js
- registry/server/config/getConfig.ts
- registry/server/migrations/20250818155232_canonical_domain_to_router_domain.ts
- registry/server/routerDomains/interfaces/index.ts
- registry/tests/config.spec.ts
- registry/tests/routerDomains.spec.ts
feat(registry/server): ability to configure canonical domain per RouterDomain entity
> feat(registry/server): ability to configure canonical domain
