- ilc/package.json
The new version has a bug-fix regarding no apps mounted until all loaded
> Update signle-spa package version

- ilc/systemjs/systemjs-override-importmap.spec.js
Change the dest to `master` when `cover/system-js-name-resolver` is going to be merged
> Cover system js override import map with karma tests

- registry/server/appRoutes/routes/createAppRoute.ts
Error example: 
```
select `routes`.`id` as `routeId`, `route_slots`.`id` as `routeSlotId`, * from `routes` inner join `route_slots` on `route_slots`.`routeId` = `routes`.`id` where `routeId` = 4 - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '* from `routes` inner join `route_slots` on `route_slots`.`routeId` = `routes`.
```
> fix: Fixed error during route creation when using MySQL as a DB

- ilc/client/handlePageTransaction.js
- ilc/client/handlePageTransaction.spec.js
transition to ms which render empty div immediately and contentful data are rendered asynchronously, so spinner is destroyed earlier then it's necessary
> fix: destroy spinner when exists contentful data

- README.md
- docs/umd_bundles_compatibility.md
- ilc/client.js
- ilc/config/custom-environment-variables.json5
- ilc/config/default.json5
- ilc/server/tailor/fetch-template.js
This also fixed "ReactDOM was loaded before React" at demo website
> feat!: fixed work with AMD modules by default

- ilc/nyc.config.js
- ilc/package.json
Just useful thing upon development to check the general coverage via terminal
> chore: added coverage text reporting npm command for ilc

- .gitignore
- registry/lde/docker-compose.yml
- registry/server/migrations/20220315155008_increase-template-size.ts
- registry/server/migrations/20220316133143_versioning-text-update.ts
Registry stores templates in DB with type text which by default has 60kb capacity. 
The issue we faced is 500 page templates with accumulated styles and images in template. Since template storage is DB I think it is reasonable to allow mediumtext type for texts
> Increase db text types

- ilc/config/default.json5
- ilc/server/app.js
Considering BC rules ignore urls params should be passed as env variable.
env variable is passed as string in node process so in runtime we should work with string
> chore: change config format due to env var is string

- registry/server/auth.ts
due to error that `openid` strategy is not registered.
> fix: attempt to fix issue when user is unable to login via openid 

- ilc/common/utils.js
- ilc/package-lock.json
- ilc/package.json
- ilc/server/app.js
- ilc/server/i18n.js
1) previously clinet.js (ILC bundle) could set header (set-cookie=i18n). it caused unpredictable bugs. 
2) update of TailorX fixes the bug with overriding ILC's Headers by fragments Headers https://github.com/StyleT/tailorx/commit/2d83fd5fb89666ee3e0c93022e5a1a54e0333d9f
> fix: correct behaviour of Header setCookie=ilc-i18n

- ilc/config/custom-environment-variables.json5
- ilc/config/default.json5
- ilc/server/app.js
- ilc/server/tailor/configs-injector.js
- ilc/server/tailor/factory.js
This is a pre-requisite for removing it at all, because it harms more right now that gives benefits (see code comment for more details).
> feat: allow to disable automatic injection of NewRelic browser monitoring on a page.

- ilc/client/CssTrackedApp.js
- ilc/client/CssTrackedApps.spec.js
This covers case when spinner is enabled and dynamic app is remounted in the different applications.
> fix: dynamic app CSS removal.

- ilc/client/Client.js
- ilc/client/TransitionManager/TransitionManager.js
- ilc/client/TransitionManager/TransitionManager.spec.js
- ilc/client/WrapApp.js
- ilc/client/WrapApp.spec.js
- ilc/client/i18n.js
- ilc/client/registerSpaApps.js
Doubled TransitionManager led to multiple events about page completion which led to a different non-trivial bugs. TransitionManager is now possible to create multiple times, but only when previous instance removes event subscriptions.
> fix: fixed doubled transition manager when wrapped app is created.

- ilc/client/BundleLoader.js
- ilc/client/BundleLoader.spec.js
- ilc/client/Client.js
- ilc/client/Sdk/SdkAdapterFactory.js
- ilc/client/Sdk/SdkFactory.js
- ilc/client/Sdk/SdkFactoryBuilder.js
- ilc/client/configuration/IlcConfigRoot.js
- ilc/client/registerSpaApps.js
* Refactor BundleLoader. Move out needDelayCss detection logic to configRoot
* Created Factories for IlcSDK and IlcSdkAdapter
* Pass SdkFactory to MainSPA to avoid ilc-sdk deps on app level
* Allow to pass SdkOption to Embedded (Dynamic Applications)
> Pass sdk app config to app bootstrap

- ilc/build/webpack.js
- ilc/package-lock.json
- ilc/package.json
During webpack minimize it discard class names, that makes impossible to use constructor.name 
during [error codes build process](https://github.com/namecheap/ilc/blob/master/ilc/client/errors/BaseError.js#L14). 
Fix keeps only error class names as is.
> fix(WebpackConfig): Prevent error class names discarding

- ilc/client/WrapApp.js
- ilc/client/registerSpaApps.js
- ilc/server/tailor/request-fragment.js
- ilc/server/tailor/request-fragment.spec.js
Wrapper receives the props from wrapped app so it allows to act based on wrapped app context
> Extend props for wrappers with wrapped apps

- ilc/common/utils.js
- ilc/package-lock.json
- ilc/package.json
- ilc/server/app.spec.js
- ilc/server/context/context.js
- ilc/server/i18n.js
- ilc/server/registry/TemplateParser.spec.js
- ilc/server/tailor/configs-injector.js
- ilc/server/tailor/configs-injector.spec.js
- registry/tests/apps.spec.ts
parsing done via parseurl library used in express for safety and performance +format fixes
> fix(ilc/server): parse invalid urls like '///'

- ilc/client/TransitionManager/TransitionManager.js
Still has minor issue in corner cases when somehow app modifies history and happens transition from itself.
> fix: add scroll state save on ilc every navigation.

- e2e/codecept.conf.js
- ilc/client/BundleLoader.js
- ilc/client/BundleLoader.spec.js
- ilc/client/Client.js
- ilc/client/CssTrackedApp.js
Allow to skip css loading in loadApp method based on option `injectGlobalCss`.
`window.ILC.loadApp` loads css via `CssTrackedApp` (backwards compatible).
Add `cssBundle` to the result object of `loadApp` method.
> feat(ilc/client): expose app configuration to loadApp  method

- ilc/client/TransitionManager/SlotRenderObserver/SlotRenderObserver.js
- ilc/client/TransitionManager/TransitionManagerForceBlockRemoving.spec.js
ILC could have a case when slot is a part of template but because of persistent state it render nothing. It that case blocker is not removed because MutationObserver waits for the visual change not a regular mutation. So proposal is allow to use a special element that signalise that slot blocker could be removed.
> feat: allow render non-visual nodes that signalise slot is ready.

- ilc/build/webpack.js
- ilc/package-lock.json
- ilc/package.json
- ilc/server/serveStatic.js
The idea is to load source maps from local env on production instead of loading file in Chrome.
> chore(ilc/client): better support for source maps on prod

- ilc/client/TransitionManager/SlotRenderObserver/SlotRenderObserver.js
- ilc/client/TransitionManager/TransitionManager.spec.js
Watch the `data-ilc-slot-ready` attribute to be able to hide the spinner when this attribute is added dynamically.
> fix(ilc/client): observe data-ilc-slot-ready attribute 

- ilc/build/webpack.test.js
- ilc/common/CacheWrapper.js
- ilc/common/CacheWrapper.spec.js
- ilc/common/utils.js
Based on code analysis and confirmed with unit test there might be a situation when the cache update is stuck and ilc will always return stale cache data.
> fix(ilc/server): don't block the cache if promise never resolves

- docker-compose.yml
- registry/package.json
- registry/server/common/services/assets/AssetsDiscovery.ts
- registry/server/common/services/assets/AssetsDiscoveryWhiteLists.ts
- registry/server/common/services/assets/assetsManifestProcessor.ts
- registry/server/runnerAssetsDiscovery.ts
- registry/tests/services/AssetsDiscovery.spec.ts
- registry/tests/utils/wait.ts
It now does not allow to have parallel update process of the same assets. 
It ensures timeouts for all the async processes to avoid long or never ending requests to db or HTTPs. 
It ensures that even if one entity process is failed - others will be successfully updated.
> fix: improve assets discovery worker stability.

- ilc/client/TransitionManager/ScrollController/ScrollController.js
- ilc/client/TransitionManager/ScrollController/ScrollController.spec.js
Replace the hashStore node variable with a getter method to handle the undefined case when instantiating ScrollController before the page ready event.
> fix(ScrollController): Replace the hashStore node variable with getter

- ilc/client/CssTrackedApp.js
- ilc/client/CssTrackedApps.spec.js
Task: [NPF-2459](https://track.namecheap.net/browse/NPF-2459)
This PR addresses an issue where CSS links injected into the DOM for embedded applications were not being removed properly when the application was unmounted. Previous attempts (see NPF-2229 and NPF-2454) addressed some scenarios, but a specific case remained where CSS was left in the DOM permanently.
Fix
This fix modifies the behavior of the **CssTrackedApp -> createNew** method in ILC to hard remove the CSS links rather than adding **markedForRemovalAttribute** attribute for Embedded application
> fix(ilc): hard remove CSS link when an embedded application is unmounted

- registry/server/templates/interfaces/index.ts
- registry/server/templates/routes/index.ts
- registry/server/templates/routes/partialUpdateTemplate.ts
- registry/server/templates/routes/validation.ts
- registry/server/templates/services/templatesRepository.ts
- registry/tests/templates.spec.ts
This PR introduces a new endpoint:
- `PATCH /api/v1/template/:name`;
- body: `{ content: string }`
The endpoint allows to update only template's content without deleting its localized versions
> feat(registry): Add endpoint to only change a template's content

- docker-compose.yml
- registry/Dockerfile
- registry/README.md
- registry/config/custom-environment-variables.ts
- registry/config/default.ts
- registry/scripts/docker-entrypoint.sh
- registry/server/app.ts
add seed option to docker
fixes #617, fixes #625
> fix(registry): fix auth in docker with http

- ilc/server/services/CspBuilderService.js
- ilc/server/services/CspBuilderService.spec.js
- registry/server/settings/interfaces/cspSchema.ts
- registry/server/settings/interfaces/index.ts
- registry/tests/settings.spec.ts
Added support for the media-src, child-src, form-action, manifest-src, object-src, script-src-attr, script-src-elem, base-uri, frame-ancestors, sandbox, and upgrade-insecure-requests CSP directives.
> support more csp directives

- registry/client/src/routerDomains/Edit.js
- registry/client/src/routerDomains/Show.js
- registry/client/src/routerDomains/dataTransform.js
- registry/server/config/getConfig.ts
- registry/server/config/transformConfig.ts
- registry/server/migrations/20250618105344_add_props_to_router_domains.ts
- registry/server/routerDomains/interfaces/index.ts
- registry/server/routerDomains/routes/createRouterDomains.ts
- registry/server/routerDomains/routes/updateRouterDomains.ts
- registry/tests/config.spec.ts
- registry/tests/routerDomains.spec.ts
- Add props and ssrProps fields to router_domains table
- Update transformConfig to apply domain props to all apps
- Update UI to allow editing domain props
- Main goal - resolve CORS issues for multi-domain deployments
> feat(registry): add domain-specific props support to router_domains
